
qtplumb:
	pyuic qtplumb.ui | sed s/table_click\(self/table_click\(self,row,col,button,point/g > qtplumb.py
	pyuic aboutbox.ui > aboutbox.py
	pyuic configbox.ui > configbox.py

demo:
	pyuic form1.ui > form1.py
